### ISSUE TITLE
helios 300 config

### ISSUE THREAD

**Issue by phfedev** [ishaan26/Hackintosh_Acer-Predator-Helios-300_G-572#1]
Hey @ishaan26 , how are you?
I have the helios 300 laptop, could you please specify your laptop cofigs?
Mine is a i7 7700HQ, 16gb ram and GTX 1060.
Have you succed intalling MacOS Catalina in your helios 300?
Have a nice day :D 👍

**Comment by ishaan26** [comment]
Hi @phfedev sorry for the late reply.
The specs are intel core i7 7700hq, 8gb ram, gtx 1050ti.

Yes I have successfully installed mac os Catalina on it but the nvidia graphics and wifi card does not work. 

Hope this helps!

**Comment by smartass08** [comment]
Hey @ishaan26 I have the same laptop (572  / i5 7300hq), Wanted to ask this - Did you try Opencore instead of clover?

**Comment by ishaan26** [comment]
Nah I have not. Its been long since I looked into hackintosh stuff. But, the Opencore website seems to have a pretty straight forward guide on how to install it. Let me know how it works out if you decide to try it.
